import {StyleSheet} from 'react-native';
import {windowHeight, windowWidth} from '../../utils/Dimensions';

const styles = StyleSheet.create ({
    container: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-end',
        alignItems: 'center',
      },
      commentBox : {
        overflowY: "auto",
        flexDirection: 'column',
        justifyContent: 'center',
        alignSelf: "center",
        alignItems: "center",
        height: windowHeight/13,
        width: windowWidth/1.1, 
        backgroundColor: "white",
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        elevation: 5,
    },
    textBox : {
      flexDirection: 'row',
      pading: 5,
      backgroundColor: "white",
  },
    timeBox : {
      flexDirection: 'column',
      pading: 5,
      left: windowWidth/3.5,
      backgroundColor: "white",
  },
      title: {
        fontFamily: 'Lexend',
        fontStyle: "normal",
        fontWeight: "600",
        fontSize: 15,
        lineHeight: 16,
        height: 16,
        color: "black",
      },
      timeTitle: {
        fontFamily: 'Lexend',
        fontStyle: "normal",
        fontWeight: "600",
        fontSize: 10,
        height: 10,
        lineHeight: 10,
        right: 0, 
        color: "black",
      },
     restaurantTitle: {
      fontFamily: 'Lexend',
      fontStyle: "normal",
      fontWeight: "900",
      fontSize: 20,
      color: "#fa706e",
      },
      inputBox : {
        flexDirection: 'row',
        justifyContent: 'center',
        alignSelf: "center",
        alignItems: "center",
        height: windowHeight/12,
        width: windowWidth, 
        backgroundColor: "white",
        elevation: 2,
    },
    buttonForms: {
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      position: "absolute",
      width: 50,
      height: 50,
      backgroundColor: "#fa706e",
      borderRadius: 80,
      elevation: 10,
      left: windowWidth/1.25,
    },
    titleButton: {
      fontFamily: 'Lexend',
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: 12,
      lineHeight: 16,
      height: 16,
      color: "white",
    },
    inputContainer: {
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      marginTop: 5,
      marginBottom: 10,
      width: windowWidth/1.05,
      height: windowHeight / 12,
      borderColor: '#ccc',
      borderRadius: 3,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fff',
    },
    iconStyle: {
      padding: 5,
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRightColor: '#ccc',
      borderRightWidth: 1,
      width: 50,
    },
    input: {
      padding: 10,
      flex: 1,
      fontFamily: 'Lexend',
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: 15,
      color: '#333',
      justifyContent: 'center',
      alignItems: 'center',
    },
    inputField: {
      padding: 10,
      marginTop: 5,
      marginBottom: 10,
      width: windowWidth / 1.5,
      height: windowHeight / 15,
      fontSize: 16,
      borderRadius: 8,
      borderWidth: 1,
    },
});

export default styles;